"""Add executions table

Revision ID: 3a917582b98a
Revises: cd1c0db65b4a
Create Date: 2026-07-31 22:48:59.488322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a917582b98a'
down_revision: Union[str, None] = 'cd1c0db65b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('response', sa.String(), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executions_agent_id'), 'executions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_executions_id'), 'executions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_executions_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_agent_id'), table_name='executions')
    op.drop_table('executions')
    # ### end Alembic commands ###
